name: Clojure CI

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:    
               push: never
               runCmd: |
                  pwd
                  ls -la .venv
                  clj -T:build ci


  make-doc:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
  
    - name: Make docs in dev container
      uses: devcontainers/ci@v0.3
      with:    
          push: never
          noCache: true      
          runCmd: clj -Adev notebooks/dev.clj 
           
    - name: fix permisions
      run: sudo chmod o+w docs/
    

    - name: check git status
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ls docs
          git status


    - name: push updated docs
      uses: stefanzweifel/git-auto-commit-action@v5
